<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-06T19:55:13 IST" name="Default suite" finished-at="2023-08-06T19:55:27 IST" duration-ms="14151">
    <groups>
    </groups>
    <test started-at="2023-08-06T19:55:13 IST" name="Default test" finished-at="2023-08-06T19:55:27 IST" duration-ms="14151">
      <class name="testcase.FirstCaseFW">
        <test-method is-config="true" signature="set_up()[pri:0, instance:testcase.FirstCaseFW@6e535154]" started-at="2023-08-06T19:55:13 IST" name="set_up" finished-at="2023-08-06T19:55:26 IST" duration-ms="12561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set_up -->
        <test-method signature="login_test(java.lang.String,java.lang.String)[pri:0, instance:testcase.FirstCaseFW@6e535154]" started-at="2023-08-06T19:55:26 IST" name="login_test" finished-at="2023-08-06T19:55:26 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot instantiate class utilities.readXLSData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot instantiate class utilities.readXLSData
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:630)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:510)
at org.testng.internal.Parameters.handleParameters(Parameters.java:763)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
... 30 more
Caused by: java.lang.NullPointerException
at utilities.readXLSData.<init>(readXLSData.java:20)
... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_test -->
        <test-method is-config="true" signature="tear_down()[pri:0, instance:testcase.FirstCaseFW@6e535154]" started-at="2023-08-06T19:55:26 IST" name="tear_down" finished-at="2023-08-06T19:55:27 IST" duration-ms="1401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear_down -->
      </class> <!-- testcase.FirstCaseFW -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
